AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # S3 Bucket for Lambda Code
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'lambda-code-bucket-${AWS::AccountId}-${AWS::Region}'

  # S3 Bucket Policy for Lambda Code
  LambdaCodeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LambdaCodeBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${LambdaCodeBucket}/*'
